# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca95851fb94ce79e0077f55e057c39bf1b1d8da7c28d553a853a9da20fbc52d0a27f344463965b0db6132f379831545f36445b81d09155ad3c6ef16be9e77ae4

test:
  secret_key_base: ad205b53aaf7311ea6b6ab9b44ce8a43c21c6aa1e9319b4566f16c8f7fc4613344dfd7160ed2e64146abeb66a61f765ef35434a627be194e523874a56ec59188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
